name: Bug Report
description: Report a bug in WormaCeptor
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
      placeholder: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this behavior?
      placeholder: |
        1. Initialize WormaCeptor with ...
        2. Open the viewer activity
        3. Navigate to ...
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: device-info
    attributes:
      label: Device info
      description: Device model, Android version, and app version.
      placeholder: |
        - Device: Pixel 8
        - Android version: 14
        - App version: 2.1.0
    validations:
      required: true

  - type: input
    id: wormaceptor-version
    attributes:
      label: WormaCeptor version
      description: Which version of WormaCeptor are you using?
      placeholder: "2.1.0"
    validations:
      required: true

  - type: dropdown
    id: integration-type
    attributes:
      label: Integration type
      description: Which implementation module are you using?
      options:
        - api-impl-persistence (Room)
        - api-impl-imdb (In-memory)
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs / stacktrace
      description: Paste any relevant crash logs or stack traces.
      render: shell
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
